/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:933154:
  kontoFelt1.formue += Float.parseFloat(textfield1.getText());
  textfield1.setText("");
} //_CODE_:button1:933154:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:384630:

  kontoFelt2.formue += Float.parseFloat(textfield1.getText());
  textfield1.setText("");
} //_CODE_:button2:384630:

public void checkbox1_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox1:756603:

} //_CODE_:checkbox1:756603:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:750817:

} //_CODE_:textfield1:750817:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 30, 100, 250, 30);
  button1.setText("Indsæt på konto 1");
  button1.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 330, 100, 250, 30);
  button2.setText("Indsæt på konto 2");
  button2.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button2.addEventHandler(this, "button2_click1");
  checkbox1 = new GCheckbox(this, 350, 35, 150, 50);
  checkbox1.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox1.setText("Check for indsætte på begge konti");
  checkbox1.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  checkbox1.setOpaque(false);
  checkbox1.addEventHandler(this, "checkbox1_clicked1");
  textfield1 = new GTextField(this, 80, 35, 120, 30, G4P.SCROLLBARS_NONE);
  textfield1.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  label1 = new GLabel(this, 0, 35, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("My label");
  label1.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  label1.setOpaque(false);
  label2 = new GLabel(this, 180, 35, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("kr.");
  label2.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  label2.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton button2; 
GCheckbox checkbox1; 
GTextField textfield1; 
GLabel label1; 
GLabel label2; 
